function getSchema(){
  return {
    MSH: [
      "MSH",
      "FieldSeparator",
      "EncodingCharacters",
      "SendingApplication",
      "SendingFacility",
      "ReceivingApplication",
      "ReceivingFacility",
      "DateTimeofMessage",
      "Security",
      "MessageType",
      "MessageControl ID",
      "ProcessingID",
      "VersionID",
      "SequenceNumber",
      "ContinuationPointer",
      "AcceptAcknowledgementType",
      "ApplicationAcknowledgementType",
      "CountryCode",
      "CharacterSet",
      "PrincipalLanguageofMessage",
      "AlternateCharacterSetHandlingScheme",
      "SendingResponsibleOrganization",
      "SendingResponsibleIndividual",
      "ReceivingResponsibleOrganization",
      "ReceivingResponsibleIndividual",
      "DateTimeofMessage",
      "Security",
      "MessageType",
      "MessageControlID",
      "ProcessingID",
      "VersionID",
      "SequenceNumber",
      "ContinuationPointer",
      "AcceptAcknowledgementType",
      "ApplicationAcknowledgementType",
      "CountryCode",
      "CharacterSet",
      "PrincipalLanguageofMessage",
      "AlternateCharacterSetHandlingScheme",
    ],
    PID: [
      "PID",
      "Setid",
      "Patientid",
      "PatientIdentifierList",
      "AlternatePatientID",
      "PatientName",
      "MothersMaidenName",
      "DateofBirth",
      "AdministrativeSex",
      "Patient lias",
      "Race",
      "PatientAddress",
      "CountyCode",
      "PhoneHome",
      "PhoneBusiness",
      "PrimaryLanguage",
      "MaritalStatus",
      "Religion",
      "PatientAccountNumber",
      "SsnNumberPatient",
      "DriversLicense",
      "MothersIdentifier",
      "EthnicGroup",
      "BirthPlace",
      "MultipleBirthIndicator",
      "BirthOrder"
    ],
    PV1:[
      "PV1",
      "Setid",
      "PatientClass",
      "AssignedPatientLocation",
      "AdmissionType",
      "PreadmitNumber",
      "PriorPatientLocation",
      "AttendingDoctor",
      "ReferringDoctor",
      "ConsultingDoctor",
      "HospitalService",
      "TemporaryLocation",
      "PreadmitTest Indicator",
      "ReadmitIndicator",
      "AdmitSource",
      "AmbulatoryStatus",
      "VipIndicator",
      "AdmittingDoctor",
      "PatientType",
      "VisitNumber",
      "FinancialClass",
      "ChargePriceIndicator",
      "CourtesyCode",
      "CreditRating",
      "ContractCode",
      "ContractEffective Date",
      "ContractAmount",
      "ContractPeriod",
      "InterestCode",
      "TransfertoBadDebtCode",
      "TransfertoBadDebtDate",
      "BadDebtAgencyCode",
      "BadDebtTransferAmount",
      "BadDebtRecoveryAmount",
      "DeleteAccountIndicator",
      "DeleteAccountDate",
      "DischargeDisposition",
      "DischargedtoLocation",
      "DietType",
      "ServicingFacility",
      "BedStatus",
      "AccountStatus",
      "PendingLocation",
      "PriorTemporary Location",
      "AdmitDateTime",
      "DischargeDateTime",
      "CurrentPatientBalance",
    ],
    IN1:[
      "IN1",
      "Set id",
      "Health Plan ID",
      "Insurance Company ID",
      "Insurance Company Name",
      "Insurance Company Address",
      "Insurance Co Contact Person",
      "Insurance Co Phone Number",
      "Group Number",
      "Group Name",
      "Insureds Group Emp ID",
      "Insureds Group Emp Name",
      "Plan Effective Date",
      "Plan Expiration Date",
      "Authorization Information",
      "Plan Type",
      "Name Of Insured",
      "Insureds relationship to patient",
      "Insureds date of birth",
      "Insureds address",
      "Assignment of Benefits",
      "Coordination of Benefits",
      "Coord of Ben. Priority",
      "Notice of Admission Flag",
      "Notice of Admission Date",
      "Report of Eligibility Flag",
      "Report of Eligibility Date",
      "Release Information Code",
      "Pre-Admit Cert",
      "Verification Date Time",
      "Verification By"
    ],
    NK1:[
      "NK1",
      "Set id",
      "Name",
      "Relationship",
      "Address",
      "Phone Number",
      "Business Phone Number",
      "Contact Role",
      "Start Date",
      "End Date",
      "Next of Kin / Associated Parties Job Title",
      "Next of Kin / Associated Parties Job Code/Class",
      "Next of Kin / Associated Parties Employee Number",
      "Organization Name - NK1",
      "Marital Status",
      "Administrative Sex",
      "Date of Birth",
      "Living Dependency",
      "Ambulatory Status",
      "Citizenship",
      "Primary Language",
      "Living Arrangement",
      "Publicity Code",
      "Protection Indicator",
      "Student Indicator",
      "Religion",
      "Mother's Maiden Name",
      "Nationality",
      "Ethnic Group",
      "Contact Reason",
      "Contact Persons Name"
    ],
    EVN:[
      "EVN",
      "Event Type Code",
      "Recorded DateTime",
      "DateTime Planned Event",
      "Event Reason Code",
      "Operator Id",
      "Event Occurred",
      "Event Facility"
    ],
    OBX:[
      "OBX",
      "Setid",
      "ValueType",
      "ObservationIdentifier",
      "ObservationSubId",
      "ObservationValue",
      "Units",
      "ReferencesRange",
      "AbnormalFlags",
      "Probability",
      "NatureofAbnormalTest",
      "ObservationResultStatus",
      "DateLastObsNormalValues",
      "UserDefinedAccessChecks",
      "DateTimeofTheObservation",
      "ProducerSId",
      "ResponsibleObserver",
      "ObservationMethod",
      "EquipmentInstanceIdentifier",
      "DateTimeofTheAnalysis"
    ],
    OBR:[
      "OBR",
      "Setid",
      "PlacerOrderNumber",
      "FillerOrderNumber",
      "UniversalServiceIdentifier",
      "Priority",
      "RequestedDateTime",
      "ObservationDateTime",
      "ObservationEndDateTime",
      "CollectionVolume",
      "CollectorIdentifier",
      "SpecimenActionCode",
      "DangerCode",
      "RelevantClinicalInfo",
      "SpecimenReceivedDateTime",
      "SpecimenSource",
      "OrderingProvider",
      "OrderCallbackPhoneNumber",
      "PlacerField1",
      "PlacerField2",
      "FillerField1",
      "FillerField2",
      "ResultsReceivedDateTime",
      "ChargeToPractice",
      "DiagnosticServSctID",
      "ResultStatus",
      "ParentResult",
      "QuantityTiming",
      "ResultCopiesTo",
      "ParentNumber",
      "TransportationMode",
      "ReasonforStudy",
      "PrincipalResultInterpreter",
      "AssistantResultInterpreter",
      "Technician",
      "Transcriptionist",
      "ScheduledDateTime",
      "NumberofSampleContainers",
      "TransportLogisticsOfCollections",
      "CollectorComment",
      "TransportArrangementResponsibility",
      "TransportArranged",
      "EscortRequired",
      "PlannedPatientTransportComment",
      "ProcedureCode",
      "ProcedureCodeModifier",
      "PlacerSupplementalServiceInformation",
      "FillerSupplementalServiceInformation"
    ]
  }

}

function getHeaders(){
  return[
    'MSH',
    'PID',
    'PV1',
    'ORC',
    'OBR',
    'OBX',
    'NTE',
    'EVN',
    'IN1',
    'NK1'
  ];
}
